// Historical analytics dashboard with archived day replay and density overlay.

let historyData=null;
let archiveEvents=[];
let map=null;
let mapLayer=null;
let densityLayer=null;
let replayLayer=null;
let replayEvents=[];
let replayIndex=0;
let replayTimer=null;
let corridorOnly=false;
let densityEnabled=false;

const CORRIDOR_REGIONS=new Set([
  'Белгородская область','Курская область','Брянская область','Орловская область',
  'Калужская область','Тульская область','Москва и Московская область',
  'Владимирская область','Рязанская область','Нижегородская область'
]);
const CORRIDOR_BOUNDS=L.latLngBounds([[50.0,31.0],[57.2,46.5]]);

async function loadJson(path){try{const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(path+' unavailable');return await response.json();}catch(error){return null;}}
async function loadHistoricalAnalytics(){return loadJson('../data/historical_analysis.json');}
async function loadArchiveEvents(){const data=await loadJson('../data/events.json');if(!Array.isArray(data))return[];const cutoff=Date.now()-24*60*60*1000;return data.filter(e=>{const t=new Date(e.published_at||0).getTime();return Number.isFinite(t)&&t<=cutoff;});}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value;}
function formatDate(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return'—';return d.toLocaleString('ru-RU');}
function localDayKey(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return'';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function renderHistoryList(id,obj){const el=document.getElementById(id);if(!el)return;el.innerHTML='';Object.entries(obj||{}).sort((a,b)=>b[1]-a[1]).slice(0,20).forEach(([name,count])=>{const item=document.createElement('div');item.className='event';item.innerHTML=`<b>${name}</b><div class="meta">${count} событий</div>`;el.appendChild(item);});}
function renderDailyChart(data){const el=document.getElementById('dailyChart');if(!el)return;const entries=Object.entries(data||{}).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))).slice(-60);if(!entries.length){el.innerHTML='<p class="muted">Пока недостаточно архивных данных.</p>';return;}const max=Math.max(...entries.map(x=>Number(x[1])||0),1);el.innerHTML=entries.map(([date,value])=>{const v=Number(value)||0,width=Math.max(2,Math.round(v/max*100));return `<div class="chart-row"><span>${date}</span><div class="chart-line"><i style="width:${width}%"></i></div><b>${v}</b></div>`;}).join('');}
function uniqueYears(events){return[...new Set(events.map(e=>new Date(e.published_at).getFullYear()).filter(Number.isFinite))].sort((a,b)=>b-a);}
function uniqueMonths(events,year){return[...new Set(events.filter(e=>!year||new Date(e.published_at).getFullYear()===Number(year)).map(e=>new Date(e.published_at).getMonth()+1))].sort((a,b)=>a-b);}
function uniqueRegions(events){return[...new Set(events.map(e=>e.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));}
function renderArchiveFilters(){const host=document.getElementById('historyFilters');if(!host)return;const years=uniqueYears(archiveEvents),regions=uniqueRegions(archiveEvents);host.innerHTML=`<label>Год<select id="historyYear"><option value="">Все</option>${years.map(y=>`<option value="${y}">${y}</option>`).join('')}</select></label><label>Месяц<select id="historyMonth"><option value="">Все</option></select></label><label>Регион<select id="historyRegion"><option value="">Все регионы</option>${regions.map(r=>`<option value="${r}">${r}</option>`).join('')}</select></label>`;const year=document.getElementById('historyYear'),month=document.getElementById('historyMonth'),region=document.getElementById('historyRegion');const refreshMonths=()=>{const months=uniqueMonths(archiveEvents,year.value);month.innerHTML=`<option value="">Все</option>${months.map(m=>`<option value="${m}">${String(m).padStart(2,'0')}</option>`).join('')}`;};year.addEventListener('change',()=>{refreshMonths();stopReplay(true);renderArchive();});month.addEventListener('change',()=>{stopReplay(true);renderArchive();});region.addEventListener('change',()=>{stopReplay(true);renderArchive();});refreshMonths();}
function filteredArchiveEvents(){const year=document.getElementById('historyYear')?.value||'',month=document.getElementById('historyMonth')?.value||'',region=document.getElementById('historyRegion')?.value||'';return archiveEvents.filter(e=>{const d=new Date(e.published_at||0);if(Number.isNaN(d.getTime()))return false;if(year&&d.getFullYear()!==Number(year))return false;if(month&&d.getMonth()+1!==Number(month))return false;if(region&&e.region!==region)return false;if(corridorOnly&&!CORRIDOR_REGIONS.has(e.region))return false;return true;});}
function ensureMap(){if(map||!window.L)return;map=L.map('historyMap').setView([55.5,45],4);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(map);mapLayer=L.layerGroup().addTo(map);densityLayer=L.layerGroup().addTo(map);replayLayer=L.layerGroup().addTo(map);}
function renderDensity(items){ensureMap();if(!densityLayer)return;densityLayer.clearLayers();if(!densityEnabled){setText('densityStatus','архивные точки');return;}const grouped=new Map();items.forEach(e=>{if(!Number.isFinite(e.lat)||!Number.isFinite(e.lon))return;const key=`${Number(e.lat).toFixed(2)}|${Number(e.lon).toFixed(2)}`;(grouped.get(key)||grouped.set(key,[]).get(key)).push(e);});const counts=[...grouped.values()].map(g=>g.length);const max=Math.max(1,...counts);grouped.forEach(group=>{const e=group[0],count=group.length,ratio=count/max,radius=10+ratio*34;L.circle([e.lat,e.lon],{radius:radius*1000,weight:1,opacity:.35,fillOpacity:.08+ratio*.22}).bindPopup(`<b>Плотность архивных фиксаций</b><br>${e.place||'район'}<br>${e.region||''}<br>${count} событий в выбранном архиве`).addTo(densityLayer);});setText('densityStatus',`зон плотности: ${grouped.size}`);}
function renderArchiveMap(items){ensureMap();if(!map||!mapLayer)return;mapLayer.clearLayers();if(replayLayer)replayLayer.clearLayers();const points=[];items.forEach(e=>{if(!Number.isFinite(e.lat)||!Number.isFinite(e.lon))return;L.circleMarker([e.lat,e.lon],{radius:6,weight:1,fillOpacity:.75}).bindPopup(`<b>${e.place||'Без НП'}</b><br>${e.region||''}<br>${formatDate(e.published_at)}<br>${e.source||''}`).addTo(mapLayer);points.push([e.lat,e.lon]);});setText('historyMapCount',`${points.length} точек`);renderDensity(items);if(corridorOnly){map.fitBounds(CORRIDOR_BOUNDS,{padding:[20,20]});}else if(points.length)map.fitBounds(points,{padding:[24,24],maxZoom:8});}
function renderCalendar(items){const el=document.getElementById('calendarList');if(!el)return;const byDay={};items.forEach(e=>{const key=localDayKey(e.published_at);if(!key)return;(byDay[key]||=[]).push(e);});const days=Object.entries(byDay).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,90);if(!days.length){el.innerHTML='<p class="muted">Нет событий в выбранном периоде.</p>';return;}el.innerHTML=days.map(([date,events])=>{const regs=new Set(events.map(e=>e.region).filter(Boolean)).size;return `<button type="button" class="calendar-day" data-day="${date}"><b>${date}</b><span>${events.length} событий · ${regs} регионов</span></button>`;}).join('');el.querySelectorAll('.calendar-day').forEach(btn=>btn.addEventListener('click',()=>selectReplayDay(btn.dataset.day,items)));}
function renderSourceQuality(items){const el=document.getElementById('sourceQuality');if(!el)return;const stats={};items.forEach(e=>{if(!e.source)return;const s=stats[e.source]||={total:0,confirmed:0,regions:new Set()};s.total+=1;if((e.confirmations||1)>1)s.confirmed+=1;if(e.region)s.regions.add(e.region);});const rows=Object.entries(stats).sort((a,b)=>b[1].total-a[1].total).slice(0,24);el.innerHTML=rows.map(([name,s])=>{const rate=s.total?Math.round(s.confirmed/s.total*100):0;return `<div class="quality-card"><b>${name}</b><span>${s.total} сообщений</span><span>${s.regions.size} регионов</span><span>${rate}% с повторным подтверждением</span></div>`;}).join('')||'<p class="muted">Нет данных.</p>';}
function selectReplayDay(day,items){stopReplay(true);replayEvents=items.filter(e=>localDayKey(e.published_at)===day&&Number.isFinite(e.lat)&&Number.isFinite(e.lon)).sort((a,b)=>new Date(a.published_at)-new Date(b.published_at));replayIndex=0;const slider=document.getElementById('replaySlider');slider.disabled=!replayEvents.length;slider.min='0';slider.max=String(Math.max(0,replayEvents.length-1));slider.value='0';setText('replayStatus',replayEvents.length?`${day} · ${replayEvents.length} точек`:`${day} · нет координат`);renderReplayStep(0);document.querySelectorAll('.calendar-day').forEach(n=>n.classList.toggle('active',n.dataset.day===day));}
function renderReplayStep(index){ensureMap();if(!replayLayer)return;replayLayer.clearLayers();if(!replayEvents.length){setText('replayLabel','—');return;}replayIndex=Math.max(0,Math.min(index,replayEvents.length-1));const upto=replayEvents.slice(0,replayIndex+1),points=[];upto.forEach((e,i)=>{const marker=L.circleMarker([e.lat,e.lon],{radius:i===replayIndex?9:5,weight:i===replayIndex?3:1,fillOpacity:i===replayIndex?.95:.45}).addTo(replayLayer);if(i===replayIndex)marker.bindPopup(`<b>${e.place||'Без НП'}</b><br>${e.region||''}<br>${formatDate(e.published_at)}<br>${e.source||''}`).openPopup();points.push([e.lat,e.lon]);});const current=replayEvents[replayIndex];setText('replayLabel',`${replayIndex+1}/${replayEvents.length} · ${new Date(current.published_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})} · ${current.place||current.region||'точка'}`);const slider=document.getElementById('replaySlider');slider.value=String(replayIndex);if(points.length)map.fitBounds(points,{padding:[35,35],maxZoom:8});}
function playReplay(){if(!replayEvents.length)return;if(replayTimer){clearInterval(replayTimer);replayTimer=null;document.getElementById('replayPlay').textContent='▶ Воспроизвести';return;}document.getElementById('replayPlay').textContent='⏸ Пауза';const speed=Number(document.getElementById('replaySpeed')?.value||1400);replayTimer=setInterval(()=>{if(replayIndex>=replayEvents.length-1){clearInterval(replayTimer);replayTimer=null;document.getElementById('replayPlay').textContent='▶ Воспроизвести';return;}renderReplayStep(replayIndex+1);},speed);}
function stopReplay(clearSelection=false){if(replayTimer){clearInterval(replayTimer);replayTimer=null;}const play=document.getElementById('replayPlay');if(play)play.textContent='▶ Воспроизвести';if(replayLayer)replayLayer.clearLayers();if(clearSelection){replayEvents=[];replayIndex=0;const slider=document.getElementById('replaySlider');if(slider){slider.value='0';slider.max='0';slider.disabled=true;}setText('replayStatus','выберите день');setText('replayLabel','—');document.querySelectorAll('.calendar-day').forEach(n=>n.classList.remove('active'));}}
function renderArchive(){const items=filteredArchiveEvents();renderArchiveMap(items);renderCalendar(items);renderSourceQuality(items);}
async function renderHistoryPage(data){historyData=data||{};setText('total',historyData.total_events||archiveEvents.length);setText('regions',Object.keys(historyData.regions||{}).length||uniqueRegions(archiveEvents).length);setText('sources',Object.keys(historyData.sources||{}).length||new Set(archiveEvents.map(e=>e.source).filter(Boolean)).size);setText('updated',historyData.generated_at?formatDate(historyData.generated_at):new Date().toLocaleString('ru-RU'));renderHistoryList('regionsList',historyData.regions||{});renderHistoryList('sourcesList',historyData.sources||{});renderDailyChart(historyData.daily||historyData.timeline||{});renderArchiveFilters();renderArchive();}
Promise.all([loadHistoricalAnalytics(),loadArchiveEvents()]).then(([analytics,events])=>{archiveEvents=events;renderHistoryPage(analytics);});
document.getElementById('resetHistory')?.addEventListener('click',()=>{corridorOnly=false;densityEnabled=false;document.getElementById('historyCorridor')?.setAttribute('aria-pressed','false');document.getElementById('densityToggle')?.setAttribute('aria-pressed','false');const corridor=document.getElementById('historyCorridor'),density=document.getElementById('densityToggle');if(corridor)corridor.textContent='Коридор → Нижний';if(density)density.textContent='Плотность: выкл';const year=document.getElementById('historyYear'),month=document.getElementById('historyMonth'),region=document.getElementById('historyRegion');if(year)year.value='';if(month)month.value='';if(region)region.value='';stopReplay(true);renderArchiveFilters();renderArchive();});
document.getElementById('historyCorridor')?.addEventListener('click',e=>{corridorOnly=!corridorOnly;e.currentTarget.setAttribute('aria-pressed',String(corridorOnly));e.currentTarget.textContent=corridorOnly?'Коридор → Нижний: вкл':'Коридор → Нижний';stopReplay(true);renderArchive();});
document.getElementById('densityToggle')?.addEventListener('click',e=>{densityEnabled=!densityEnabled;e.currentTarget.setAttribute('aria-pressed',String(densityEnabled));e.currentTarget.textContent=densityEnabled?'Плотность: вкл':'Плотность: выкл';renderDensity(filteredArchiveEvents());});
document.getElementById('replayPlay')?.addEventListener('click',playReplay);
document.getElementById('replayStop')?.addEventListener('click',()=>{if(replayEvents.length)renderReplayStep(0);stopReplay(false);});
document.getElementById('replaySlider')?.addEventListener('input',e=>{if(replayTimer){clearInterval(replayTimer);replayTimer=null;document.getElementById('replayPlay').textContent='▶ Воспроизвести';}renderReplayStep(Number(e.target.value));});
document.getElementById('replaySpeed')?.addEventListener('change',()=>{if(replayTimer){clearInterval(replayTimer);replayTimer=null;document.getElementById('replayPlay').textContent='▶ Воспроизвести';}});
window.HistoricalAnalytics={loadHistoricalAnalytics};